version: '2.1'

services:

 nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    user: root
    privileged: true
    restart: unless-stopped
    ports:
      - 9100:9100
    labels:
      org.label-schema.group: "monitoring"

 cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - 8080:8080
    labels:
      org.label-schema.group: "monitoring"
