version: '2'

services:
   nginx:
     image: nginx
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
     restart: always
     #environment:
      #- IP_ADDRESS=localhost
     ports:
      - 80:80
