- easy_install:
    name: pip
    state: latest


- name: Download docker shell file
  get_url:
    url: https://releases.rancher.com/install-docker/1.13.sh
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: +x
    remote_src: yes

- name: install docker
  shell: /home/ec2-user/1.13.sh


- name: add user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
    #sudo: true

- name: restart docker
  service:
    name: docker
    state: restarted

- name: install docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.20.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: +x

- name: install docker compose package
  pip:
    name: docker-compose
    version: 1.20.1
    executable: /bin/pip

- name: install the latest version of git
  yum:
    name: git
    state: latest
