---
- hosts: all
  become: true
  roles:
     - { role: docker,
         tags: docker1 }
     - { role: wordpress,
         tags: wordpress1 }
     - { role: prometheus,
         tags: prometheus1 }
     - { role: nginx,
         tags: nginx1 }
